// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDouH4_UpJ2EDbWsmwZtkrUGsQ-7mO1V5k',
    appId: '1:722338354655:android:b58f8396178fefd183a06a',
    messagingSenderId: '722338354655',
    projectId: 'maslakfilm-f479b',
    storageBucket: 'maslakfilm-f479b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe4Re_V4fuINZVjCTQw5R6QE_0H98sfW8',
    appId: '1:722338354655:ios:676f0b9887afc39283a06a',
    messagingSenderId: '722338354655',
    projectId: 'maslakfilm-f479b',
    storageBucket: 'maslakfilm-f479b.firebasestorage.app',
    iosBundleId: 'com.maslakfilm.ets',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDouH4_UpJ2EDbWsmwZtkrUGsQ-7mO1V5k',
    appId: '1:722338354655:web:61c2eabb44067dea83a06a',
    messagingSenderId: '722338354655',
    projectId: 'maslakfilm-f479b',
    authDomain: 'maslakfilm-f479b.firebaseapp.com',
    storageBucket: 'maslakfilm-f479b.firebasestorage.app',
  );

}
